export const WORDING_LIBRARY = [
  {
    category: 'Updates',
    description: 'Launches, releases, and project news',
    items: [
      '[Project] just went live.',
      '[Project] testnet is finally live.',
      '[Project] just opened access to early users.',
      '[Project] officially launched [feature] today.',
      '[Project] just made its next move.',
      'The wait is over: [Project] is live.',
      'If you are watching [Project], this update matters.',
    ],
  },
  {
    category: 'Opportunities',
    description: 'Early access and actionable alpha',
    items: [
      'If you are interested in [category], do not skip this one.',
      'This could be worth exploring early.',
      'If you are farming [Project], pay attention.',
      'This is one testnet I would keep on the radar.',
      'Do not wait until [Project] gets crowded.',
      'Found another early opportunity worth checking.',
      'This might be worth a few minutes of your time.',
    ],
  },
  {
    category: 'Curiosity',
    description: 'Open loops that stop the scroll',
    items: [
      'The interesting part is not what you think.',
      'Most people will focus on the wrong thing here.',
      'Here is what caught my attention.',
      'This solves a problem most people overlook.',
      'This is not just another [category] project.',
      'The product is simple. The thesis is not.',
      'Here is what I learned after testing it.',
    ],
  },
  {
    category: 'Personal',
    description: 'First-hand experience and observations',
    items: [
      'I have been testing [Project] lately.',
      'I spent some time exploring [Project] today.',
      'I finally decided to dig deeper into [Project].',
      'I tried [Project] so you do not have to.',
      'I tested the entire onboarding flow.',
      'After spending time with [Project], here is my take.',
    ],
  },
  {
    category: 'Research',
    description: 'Evidence-led framing and findings',
    items: [
      'I reviewed the docs, product, and current traction.',
      'Three details stood out during my research:',
      'The numbers tell a more interesting story.',
      'A closer look at the docs reveals the real thesis.',
      'Here is the signal I found beneath the noise.',
      'Before forming a view, I checked the fundamentals.',
    ],
  },
  {
    category: 'Context',
    description: 'Simple project and market explainers',
    items: [
      '[Project] is building...',
      'For anyone new to [Project], here is the simple version.',
      'In simple terms, [Project] is trying to...',
      'At its core, [Project] is...',
      'The main problem they are trying to solve is...',
      'Here is why this matters.',
      'Before the tasks, here is what [Project] actually does.',
    ],
  },
  {
    category: 'Features',
    description: 'Benefits and differentiators',
    items: [
      'The feature that caught my attention:',
      'The standout feature is...',
      'What separates this from other [projects] is...',
      'Instead of [old method], [Project] uses...',
      'The practical benefit is...',
      'The concept is strong; execution will matter.',
    ],
  },
  {
    category: 'Tutorials',
    description: 'Clear step-by-step instructions',
    items: [
      'Here is how to get started:',
      'Getting started is straightforward:',
      'Step 1: Create your account.\nStep 2: Connect your wallet.\nStep 3: Claim testnet tokens.',
      'Start with the official app, then connect your wallet.',
      'Complete the onboarding before moving to the main tasks.',
      'Use the official link only.',
    ],
  },
  {
    category: 'Checklist',
    description: 'Scannable tasks and safeguards',
    items: [
      'Before you start, check these off:',
      '→ Create an account\n→ Connect your wallet\n→ Switch to [network]\n→ Claim testnet tokens\n→ Complete the first task',
      '→ Verify the official URL\n→ Check the network\n→ Review every signature',
      'Double-check the contract before signing.',
      'Save your transaction links for later.',
      'Return weekly to check for new tasks.',
    ],
  },
  {
    category: 'Takes',
    description: 'Personal verdicts with useful nuance',
    items: [
      'Personally, I think this is worth watching.',
      'My first impression is positive.',
      'The product has potential, but execution will matter.',
      'I would rather test the product than speculate.',
      'I would treat this as an early experiment.',
      'For now, I am cautiously optimistic.',
    ],
  },
  {
    category: 'CTAs',
    description: 'Natural prompts for action and replies',
    items: [
      'Anyone else testing this?',
      'Would you try this?',
      'What is your take?',
      'Bookmark this guide if you plan to try it.',
      'Save this if you are farming the testnet.',
      'I will keep testing and share what I find.',
    ],
  },
  {
    category: 'Transitions',
    description: 'Connect ideas without losing momentum',
    items: [
      'But that is only part of the story.',
      'Now, here is where it gets interesting.',
      'The opportunity becomes clearer when you look closer.',
      'That brings us to the practical part.',
      'There is one important tradeoff to consider.',
      'With the context covered, let us look at the process.',
    ],
  },
  {
    category: 'Analysis',
    description: 'Balanced conclusions and risk framing',
    items: [
      'The upside is clear, but so are the risks.',
      'The strongest signal here is...',
      'The weak point in the current model is...',
      'Adoption will depend on two things:',
      'This matters because it changes...',
      'The thesis works if [condition] holds true.',
      'Watch the product metrics, not only the narrative.',
    ],
  },
];