export const WORDING_LIBRARY = [
  {
    category: 'Hook',
    description: 'Stop the scroll in the first one or two lines',
    items: [
      '[Project] just went live.',
      '[Project] testnet is finally live.',
      '[Project] just opened access.',
      '[Project] has officially launched [feature].',
      'The wait is over — [Project] is live.',
      'If you are watching [Project], this update matters.',
      'If you are interested in [category], do not skip this one.',
      'This could be worth exploring early.',
      'If you are farming [Project], pay attention.',
      'This is one testnet I would keep on the radar.',
      'Early users might want to look at this.',
      'Found another early opportunity worth checking.',
      'The interesting part is not what you think.',
      'Most people will probably focus on the wrong thing here.',
      'Here is what caught my attention.',
      'This solves a problem most people overlook.',
      'This is not just another [category] project.',
      'The product is simple. The thesis is not.',
      'I think the market is overlooking this.',
      'Here is what I found after digging into [topic].',
    ],
  },
  {
    category: 'Context',
    description: 'Explain what happened or what the project does',
    items: [
      '[Project] is building...',
      'For anyone new to [Project], here is the simple version.',
      'In simple terms, [Project] is trying to...',
      'The basic idea is straightforward:',
      'At its core, [Project] is...',
      'The project is focused on...',
      'The main problem they are trying to solve is...',
      'The project recently announced...',
      "According to the team's latest update...",
      'The latest update is that...',
      'The testnet currently allows users to...',
      'The product is designed to...',
      'The protocol works by...',
      'If you are unfamiliar with [Project]...',
      'Here is the context before you start:',
      'Before getting into the tasks, here is what [Project] actually does.',
      'So what exactly is [Project]?',
      'The main thing to understand is...',
      'The current version lets users...',
      'The latest version introduces...',
    ],
  },
  {
    category: 'Why',
    description: 'Connect the update to why the reader should care',
    items: [
      'Here is why this matters.',
      'This matters because...',
      'The important part is...',
      'The reason users may care is...',
      'For users, the main opportunity is...',
      'For developers, the interesting part is...',
      'For DeFi users, this could be useful because...',
      'For early users, the key point is...',
      'The part worth watching is...',
      'Why does this matter?',
      'In practice, this means...',
      'For users, that means...',
      'For developers, that means...',
      'The practical benefit is...',
      'The potential advantage is...',
      'The interesting consequence is...',
      'This could make [action] easier because...',
      'This matters because users do not have to...',
      'This changes the experience by...',
      'And this is why it matters.',
    ],
  },
  {
    category: 'Feature',
    description: 'Highlight the standout detail worth remembering',
    items: [
      'The feature that caught my attention:',
      'The part I am most interested in:',
      'The standout feature is...',
      'The most interesting part is...',
      'One feature worth testing is...',
      'Here is what makes it different:',
      'The key difference is...',
      'What separates this from other [projects] is...',
      'The feature I would pay attention to is...',
      'The mechanism I find most interesting is...',
      'Instead of [old method], [Project] uses...',
      'Rather than relying on [X], the protocol uses...',
      'Unlike traditional [X], this approach...',
      'The protocol takes a different approach to...',
      'This is where [Project] gets creative.',
      'The design choice that stood out to me was...',
      'One unusual mechanic is...',
      'The mechanic worth understanding is...',
      'This is probably the feature I would test first.',
      'But there is a catch.',
    ],
  },
  {
    category: 'Action',
    description: 'Give the reader a clear process or next step',
    items: [
      'Here is how to get started:',
      'Here is how you can try it:',
      'Getting started is pretty simple:',
      'If you want to test it, start here:',
      'Here is the easiest way to begin:',
      'You can get started in a few steps:',
      'The basic process looks like this:',
      'If you are new, follow these steps:',
      'Here is the full flow:',
      '→ Create an account',
      '→ Connect your wallet',
      '→ Switch to [network]',
      '→ Grab testnet tokens',
      '→ Complete the first task',
      '→ Submit your work',
      '→ Confirm the transaction',
      '→ Check your points',
      '→ Join the community',
      'Step 1: Create your account.',
      'Step 2: Connect your wallet.',
    ],
  },
  {
    category: 'Details',
    description: 'Prevent mistakes and clarify key requirements',
    items: [
      'Before you start, make sure you have...',
      'You will need the following:',
      'Make sure you are using the correct network.',
      'Double-check the contract before signing.',
      'Use the official link only.',
      'Do not connect your wallet through random links.',
      'Do not rush through the submission process.',
      'Make sure every task is submitted correctly.',
      'Important: use the same wallet you registered with.',
      'Do not switch wallets midway unless the rules allow it.',
      'Check whether a referral code is required.',
      'Some users may need an invite code.',
      'Access may be rolled out gradually.',
      'Read the eligibility requirements before starting.',
      'Check the deadline before submitting.',
      'Do not make this mistake:',
      'Be careful with...',
      'Do not skip this step.',
      'Do not sign transactions you do not understand.',
      'Do not assume an airdrop is confirmed unless officially announced.',
    ],
  },
  {
    category: 'Take',
    description: 'Add a clear personal observation or opinion',
    items: [
      'Personally, I think this is worth watching.',
      'My first impression is positive.',
      'So far, the experience has been pretty smooth.',
      'The onboarding was simpler than I expected.',
      'The product is interesting, but it is still early.',
      'The feature I am most curious about is...',
      'I will be watching how this develops.',
      'The product has potential, but execution will matter.',
      'I would rather test the product than speculate.',
      'I am more interested in the product than the hype.',
      'The thesis makes sense to me, but there is still a lot to prove.',
      'I think the early stage is what makes this interesting.',
      'I would keep this on the watchlist.',
      'I am curious to see what happens next.',
      'The biggest takeaway for me is...',
      'After testing it, my main takeaway is...',
      'The strongest part of the product is...',
      'I would treat this as an early experiment.',
      'There is still a lot we do not know.',
      'For now, I am cautiously optimistic.',
    ],
  },
  {
    category: 'CTA',
    description: 'Invite a natural reply, save, share, or next action',
    items: [
      'Anyone else testing this?',
      'Would you try this?',
      'Are you participating?',
      'What do you think about this?',
      'Would you use this product?',
      'Have you tried it yet?',
      'Who else is exploring this ecosystem?',
      'What is your take?',
      'Let me know how it goes.',
      'Tell me if you run into any issues.',
      'Drop your experience below.',
      'Did you notice anything I missed?',
      'What feature are you testing first?',
      'Do you think this solves a real problem?',
      'What am I missing?',
      'Save this for later.',
      'Bookmark this guide if you are planning to try it.',
      'Share this with someone testing [Project].',
      'Keep this checklist handy.',
      'I will keep testing and share what I find.',
    ],
  },
  {
    category: 'Transitions',
    description: 'Move cleanly between framework sections',
    items: [
      'So, what exactly is it?',
      'But here is where it gets interesting.',
      'Now for the important part.',
      'Here is what you actually need to know.',
      'So how does it work?',
      'Here is how the system works.',
      'Now let us get into the tasks.',
      'Here is where you can start.',
      'If you are planning to participate, read this.',
      'Before you start, there is one thing to know.',
      'This is where things get different.',
      'That brings us to the main point.',
      'So what does this mean for users?',
      'Now let us break it down.',
      'Let us make this simple.',
      'In plain English:',
      'What this means in practice:',
      'However, there is a catch.',
      'One thing to keep in mind:',
      'Moving on to the actual process:',
    ],
  },
  {
    category: 'Analysis',
    description: 'Frame evidence, interpretation, risks, and signals',
    items: [
      'I looked into [X] and found something interesting.',
      'I went through the data on [topic].',
      'I analyzed [X] projects to understand...',
      'I compared [X] projects across...',
      'One trend stood out immediately.',
      'The numbers show something interesting.',
      'The data tells a different story.',
      'After digging into the numbers...',
      'The biggest pattern I noticed was...',
      'The same trend appears across several projects.',
      'The funding numbers tell us...',
      'The investor mix is worth looking at.',
      'The data suggests...',
      'But data alone does not tell the whole story.',
      'This is where context matters.',
      'The real question is whether...',
      'My current takeaway is...',
      'This suggests a broader trend.',
      'I would want to see more data before reaching a conclusion.',
      'The biggest unanswered question is...',
    ],
  },
];